export type JlptLevel = "N5" | "N4" | "N3" | "N2" | "N1";

export interface RoleplayContext {
  situation: string;
  ai_role: string;
  initial_msg: string;
  mission_keywords?: string[];
}

export interface Word {
  id: string;
  level: JlptLevel;
  kanji: string;
  kana: string;
  meaning: string;
  pos?: string;
  example_ja?: string;
  example_reading?: string;
  example_ko?: string;
  pitch_pattern?: number[];
  roleplay_context?: RoleplayContext;
}

export const STAGE_SIZE = 15;

export const N5_WORDS: Word[] = [
  { id: "n5-001", level: "N5", kanji: "私", kana: "わたし", meaning: "나, 저", pos: "대명사",
    pitch_pattern: [0, 1, 1],
    example_ja: "私は学生です。", example_reading: "わたしはがくせいです。", example_ko: "저는 학생입니다.",
    roleplay_context: {
      situation: "도쿄 카페에서 옆자리 일본인과 자기소개를 하는 상황",
      ai_role: "친절한 일본인 대학생",
      initial_msg: "こんにちは！はじめまして。お名前は何ですか？",
      mission_keywords: ["私", "学生", "韓国"],
    } },
  { id: "n5-002", level: "N5", kanji: "貴方", kana: "あなた", meaning: "당신", pos: "대명사",
    example_ja: "あなたは誰ですか。", example_reading: "あなたはだれですか。", example_ko: "당신은 누구입니까?" },
  { id: "n5-003", level: "N5", kanji: "人", kana: "ひと", meaning: "사람", pos: "명사",
    example_ja: "あの人は先生です。", example_reading: "あのひとはせんせいです。", example_ko: "저 사람은 선생님입니다." },
  { id: "n5-004", level: "N5", kanji: "学生", kana: "がくせい", meaning: "학생", pos: "명사",
    example_ja: "私は大学の学生です。", example_reading: "わたしはだいがくのがくせいです。", example_ko: "저는 대학교 학생입니다." },
  { id: "n5-005", level: "N5", kanji: "先生", kana: "せんせい", meaning: "선생님", pos: "명사",
    example_ja: "先生に質問します。", example_reading: "せんせいにしつもんします。", example_ko: "선생님께 질문합니다." },
  { id: "n5-006", level: "N5", kanji: "友達", kana: "ともだち", meaning: "친구", pos: "명사",
    example_ja: "友達と映画を見ます。", example_reading: "ともだちとえいがをみます。", example_ko: "친구와 영화를 봅니다." },
  { id: "n5-007", level: "N5", kanji: "家族", kana: "かぞく", meaning: "가족", pos: "명사",
    example_ja: "家族は四人です。", example_reading: "かぞくはよにんです。", example_ko: "가족은 네 명입니다." },
  { id: "n5-008", level: "N5", kanji: "父", kana: "ちち", meaning: "(나의) 아버지", pos: "명사",
    example_ja: "父は会社員です。", example_reading: "ちちはかいしゃいんです。", example_ko: "아버지는 회사원입니다." },
  { id: "n5-009", level: "N5", kanji: "母", kana: "はは", meaning: "(나의) 어머니", pos: "명사",
    example_ja: "母は料理が上手です。", example_reading: "はははりょうりがじょうずです。", example_ko: "어머니는 요리를 잘합니다." },
  { id: "n5-010", level: "N5", kanji: "兄", kana: "あに", meaning: "(나의) 형, 오빠", pos: "명사",
    example_ja: "兄は東京にいます。", example_reading: "あにはとうきょうにいます。", example_ko: "형은 도쿄에 있습니다." },
  { id: "n5-011", level: "N5", kanji: "姉", kana: "あね", meaning: "(나의) 누나, 언니", pos: "명사",
    example_ja: "姉は二十五歳です。", example_reading: "あねはにじゅうごさいです。", example_ko: "누나는 25살입니다." },
  { id: "n5-012", level: "N5", kanji: "弟", kana: "おとうと", meaning: "남동생", pos: "명사",
    example_ja: "弟は中学生です。", example_reading: "おとうとはちゅうがくせいです。", example_ko: "남동생은 중학생입니다." },
  { id: "n5-013", level: "N5", kanji: "妹", kana: "いもうと", meaning: "여동생", pos: "명사",
    example_ja: "妹は犬が好きです。", example_reading: "いもうとはいぬがすきです。", example_ko: "여동생은 개를 좋아합니다." },
  { id: "n5-014", level: "N5", kanji: "犬", kana: "いぬ", meaning: "개", pos: "명사",
    example_ja: "私の犬は大きいです。", example_reading: "わたしのいぬはおおきいです。", example_ko: "내 개는 큽니다." },
  { id: "n5-015", level: "N5", kanji: "猫", kana: "ねこ", meaning: "고양이", pos: "명사",
    example_ja: "猫が窓の上にいます。", example_reading: "ねこがまどのうえにいます。", example_ko: "고양이가 창문 위에 있습니다." },
  { id: "n5-016", level: "N5", kanji: "魚", kana: "さかな", meaning: "물고기, 생선", pos: "명사",
    pitch_pattern: [0, 1, 1],
    example_ja: "魚を食べます。", example_reading: "さかなをたべます。", example_ko: "생선을 먹습니다.",
    roleplay_context: {
      situation: "도쿄 츠키지의 작은 회전초밥 가게에서 주문하는 상황",
      ai_role: "활기찬 초밥 가게 점원",
      initial_msg: "いらっしゃい！今日のおすすめのお魚、たくさんありますよ。何にしましょうか？",
      mission_keywords: ["魚", "好き", "ください"],
    } },
  { id: "n5-017", level: "N5", kanji: "鳥", kana: "とり", meaning: "새, 닭", pos: "명사",
    example_ja: "鳥が空を飛びます。", example_reading: "とりがそらをとびます。", example_ko: "새가 하늘을 납니다." },
  { id: "n5-018", level: "N5", kanji: "水", kana: "みず", meaning: "물", pos: "명사",
    example_ja: "水を飲みたいです。", example_reading: "みずをのみたいです。", example_ko: "물을 마시고 싶습니다." },
  { id: "n5-019", level: "N5", kanji: "火", kana: "ひ", meaning: "불", pos: "명사",
    example_ja: "火に気をつけて。", example_reading: "ひにきをつけて。", example_ko: "불 조심해요." },
  { id: "n5-020", level: "N5", kanji: "木", kana: "き", meaning: "나무", pos: "명사",
    example_ja: "公園に木がたくさんあります。", example_reading: "こうえんにきがたくさんあります。", example_ko: "공원에 나무가 많이 있습니다." },
  { id: "n5-021", level: "N5", kanji: "花", kana: "はな", meaning: "꽃", pos: "명사",
    example_ja: "花がきれいですね。", example_reading: "はながきれいですね。", example_ko: "꽃이 예쁘네요." },
  { id: "n5-022", level: "N5", kanji: "山", kana: "やま", meaning: "산", pos: "명사",
    example_ja: "週末に山に登ります。", example_reading: "しゅうまつにやまにのぼります。", example_ko: "주말에 산에 오릅니다." },
  { id: "n5-023", level: "N5", kanji: "川", kana: "かわ", meaning: "강", pos: "명사",
    example_ja: "川で泳ぎました。", example_reading: "かわでおよぎました。", example_ko: "강에서 수영했습니다." },
  { id: "n5-024", level: "N5", kanji: "海", kana: "うみ", meaning: "바다", pos: "명사",
    example_ja: "夏に海へ行きます。", example_reading: "なつにうみへいきます。", example_ko: "여름에 바다에 갑니다." },
  { id: "n5-025", level: "N5", kanji: "空", kana: "そら", meaning: "하늘", pos: "명사",
    example_ja: "空が青いです。", example_reading: "そらがあおいです。", example_ko: "하늘이 푸릅니다." },
  { id: "n5-026", level: "N5", kanji: "雨", kana: "あめ", meaning: "비", pos: "명사",
    example_ja: "今日は雨が降ります。", example_reading: "きょうはあめがふります。", example_ko: "오늘은 비가 옵니다." },
  { id: "n5-027", level: "N5", kanji: "雪", kana: "ゆき", meaning: "눈(snow)", pos: "명사",
    example_ja: "雪がたくさん降りました。", example_reading: "ゆきがたくさんふりました。", example_ko: "눈이 많이 내렸습니다." },
  { id: "n5-028", level: "N5", kanji: "風", kana: "かぜ", meaning: "바람", pos: "명사",
    example_ja: "強い風が吹いています。", example_reading: "つよいかぜがふいています。", example_ko: "강한 바람이 불고 있습니다." },
  { id: "n5-029", level: "N5", kanji: "今日", kana: "きょう", meaning: "오늘", pos: "명사",
    example_ja: "今日はいい天気です。", example_reading: "きょうはいいてんきです。", example_ko: "오늘은 좋은 날씨입니다." },
  { id: "n5-030", level: "N5", kanji: "明日", kana: "あした", meaning: "내일", pos: "명사",
    example_ja: "明日また会いましょう。", example_reading: "あしたまたあいましょう。", example_ko: "내일 또 만납시다." },
  { id: "n5-031", level: "N5", kanji: "昨日", kana: "きのう", meaning: "어제", pos: "명사",
    pitch_pattern: [1, 0, 0],
    example_ja: "昨日映画を見ました。", example_reading: "きのうえいがをみました。", example_ko: "어제 영화를 봤습니다.",
    roleplay_context: {
      situation: "일본 친구와 카페에서 주말 이야기를 나누는 상황",
      ai_role: "수다스러운 일본인 친구",
      initial_msg: "週末、何してた？昨日とか面白いことあった？",
      mission_keywords: ["昨日", "映画", "友達"],
    } },
  { id: "n5-032", level: "N5", kanji: "今", kana: "いま", meaning: "지금", pos: "명사",
    example_ja: "今、何時ですか。", example_reading: "いま、なんじですか。", example_ko: "지금 몇 시예요?" },
  { id: "n5-033", level: "N5", kanji: "朝", kana: "あさ", meaning: "아침", pos: "명사",
    example_ja: "朝ごはんを食べました。", example_reading: "あさごはんをたべました。", example_ko: "아침밥을 먹었습니다." },
  { id: "n5-034", level: "N5", kanji: "昼", kana: "ひる", meaning: "낮, 점심", pos: "명사",
    example_ja: "昼休みは一時間です。", example_reading: "ひるやすみはいちじかんです。", example_ko: "점심시간은 1시간입니다." },
  { id: "n5-035", level: "N5", kanji: "夜", kana: "よる", meaning: "밤", pos: "명사",
    example_ja: "夜遅くまで勉強しました。", example_reading: "よるおそくまでべんきょうしました。", example_ko: "밤 늦게까지 공부했습니다." },
  { id: "n5-036", level: "N5", kanji: "時間", kana: "じかん", meaning: "시간", pos: "명사",
    example_ja: "時間がありません。", example_reading: "じかんがありません。", example_ko: "시간이 없습니다." },
  { id: "n5-037", level: "N5", kanji: "学校", kana: "がっこう", meaning: "학교", pos: "명사",
    example_ja: "毎日学校へ行きます。", example_reading: "まいにちがっこうへいきます。", example_ko: "매일 학교에 갑니다." },
  { id: "n5-038", level: "N5", kanji: "会社", kana: "かいしゃ", meaning: "회사", pos: "명사",
    example_ja: "会社は駅の近くです。", example_reading: "かいしゃはえきのちかくです。", example_ko: "회사는 역 근처입니다." },
  { id: "n5-039", level: "N5", kanji: "家", kana: "いえ", meaning: "집", pos: "명사",
    example_ja: "家でゆっくり休みます。", example_reading: "いえでゆっくりやすみます。", example_ko: "집에서 푹 쉽니다." },
  { id: "n5-040", level: "N5", kanji: "部屋", kana: "へや", meaning: "방", pos: "명사",
    example_ja: "私の部屋は広いです。", example_reading: "わたしのへやはひろいです。", example_ko: "내 방은 넓습니다." },
  { id: "n5-041", level: "N5", kanji: "駅", kana: "えき", meaning: "역(station)", pos: "명사",
    example_ja: "駅で友達に会います。", example_reading: "えきでともだちにあいます。", example_ko: "역에서 친구를 만납니다." },
  { id: "n5-042", level: "N5", kanji: "電車", kana: "でんしゃ", meaning: "전철", pos: "명사",
    example_ja: "電車で会社へ行きます。", example_reading: "でんしゃでかいしゃへいきます。", example_ko: "전철로 회사에 갑니다." },
  { id: "n5-043", level: "N5", kanji: "車", kana: "くるま", meaning: "자동차", pos: "명사",
    example_ja: "新しい車を買いました。", example_reading: "あたらしいくるまをかいました。", example_ko: "새 자동차를 샀습니다." },
  { id: "n5-044", level: "N5", kanji: "自転車", kana: "じてんしゃ", meaning: "자전거", pos: "명사",
    example_ja: "自転車で学校へ行きます。", example_reading: "じてんしゃでがっこうへいきます。", example_ko: "자전거로 학교에 갑니다." },
  { id: "n5-045", level: "N5", kanji: "本", kana: "ほん", meaning: "책", pos: "명사",
    example_ja: "本を読むのが好きです。", example_reading: "ほんをよむのがすきです。", example_ko: "책 읽는 것을 좋아합니다." },
  { id: "n5-046", level: "N5", kanji: "新聞", kana: "しんぶん", meaning: "신문", pos: "명사",
    pitch_pattern: [0, 1, 1, 1],
    example_ja: "毎朝新聞を読みます。", example_reading: "まいあさしんぶんをよみます。", example_ko: "매일 아침 신문을 읽습니다.",
    roleplay_context: {
      situation: "도쿄 호텔 프론트에서 체크인하며 안내를 받는 상황",
      ai_role: "공손한 호텔 프런트 직원",
      initial_msg: "ようこそ！チェックインですね。お部屋の鍵をお渡しします。何かご質問はございますか？",
      mission_keywords: ["部屋", "新聞", "ありがとう"],
    } },
  { id: "n5-047", level: "N5", kanji: "鉛筆", kana: "えんぴつ", meaning: "연필", pos: "명사",
    example_ja: "鉛筆で書きます。", example_reading: "えんぴつでかきます。", example_ko: "연필로 씁니다." },
  { id: "n5-048", level: "N5", kanji: "机", kana: "つくえ", meaning: "책상", pos: "명사",
    example_ja: "机の上に本があります。", example_reading: "つくえのうえにほんがあります。", example_ko: "책상 위에 책이 있습니다." },
  { id: "n5-049", level: "N5", kanji: "椅子", kana: "いす", meaning: "의자", pos: "명사",
    example_ja: "椅子に座ってください。", example_reading: "いすにすわってください。", example_ko: "의자에 앉으세요." },
  { id: "n5-050", level: "N5", kanji: "窓", kana: "まど", meaning: "창문", pos: "명사",
    example_ja: "窓を開けてもいいですか。", example_reading: "まどをあけてもいいですか。", example_ko: "창문을 열어도 될까요?" },
  { id: "n5-051", level: "N5", kanji: "扉", kana: "とびら", meaning: "문, 문짝", pos: "명사",
    example_ja: "扉を閉めてください。", example_reading: "とびらをしめてください。", example_ko: "문을 닫아 주세요." },
  { id: "n5-052", level: "N5", kanji: "食べ物", kana: "たべもの", meaning: "음식", pos: "명사",
    example_ja: "好きな食べ物は何ですか。", example_reading: "すきなたべものはなんですか。", example_ko: "좋아하는 음식은 무엇입니까?" },
  { id: "n5-053", level: "N5", kanji: "飲み物", kana: "のみもの", meaning: "음료", pos: "명사",
    example_ja: "冷たい飲み物が欲しいです。", example_reading: "つめたいのみものがほしいです。", example_ko: "차가운 음료가 마시고 싶습니다." },
  { id: "n5-054", level: "N5", kanji: "ご飯", kana: "ごはん", meaning: "밥, 식사", pos: "명사",
    example_ja: "一緒にご飯を食べましょう。", example_reading: "いっしょにごはんをたべましょう。", example_ko: "같이 밥 먹읍시다." },
  { id: "n5-055", level: "N5", kanji: "肉", kana: "にく", meaning: "고기", pos: "명사",
    example_ja: "肉より魚が好きです。", example_reading: "にくよりさかながすきです。", example_ko: "고기보다 생선을 좋아합니다." },
  { id: "n5-056", level: "N5", kanji: "野菜", kana: "やさい", meaning: "야채", pos: "명사",
    example_ja: "野菜をたくさん食べます。", example_reading: "やさいをたくさんたべます。", example_ko: "야채를 많이 먹습니다." },
  { id: "n5-057", level: "N5", kanji: "果物", kana: "くだもの", meaning: "과일", pos: "명사",
    example_ja: "りんごは私の好きな果物です。", example_reading: "りんごはわたしのすきなくだものです。", example_ko: "사과는 제가 좋아하는 과일입니다." },
  { id: "n5-058", level: "N5", kanji: "茶", kana: "おちゃ", meaning: "차(tea)", pos: "명사",
    example_ja: "お茶を飲みませんか。", example_reading: "おちゃをのみませんか。", example_ko: "차 한잔 하지 않을래요?" },
  { id: "n5-059", level: "N5", kanji: "牛乳", kana: "ぎゅうにゅう", meaning: "우유", pos: "명사",
    example_ja: "毎朝牛乳を飲みます。", example_reading: "まいあさぎゅうにゅうをのみます。", example_ko: "매일 아침 우유를 마십니다." },
  { id: "n5-060", level: "N5", kanji: "卵", kana: "たまご", meaning: "달걀", pos: "명사",
    example_ja: "卵を二つください。", example_reading: "たまごをふたつください。", example_ko: "달걀 두 개 주세요." },
  { id: "n5-061", level: "N5", kanji: "行く", kana: "いく", meaning: "가다", pos: "동사",
    pitch_pattern: [0, 1],
    example_ja: "明日東京へ行きます。", example_reading: "あしたとうきょうへいきます。", example_ko: "내일 도쿄에 갑니다.",
    roleplay_context: {
      situation: "JR역 안내데스크에서 목적지로 가는 길을 묻는 상황",
      ai_role: "친절한 역무원",
      initial_msg: "ご案内できますよ！どちらまで行かれますか？",
      mission_keywords: ["行く", "電車", "駅"],
    } },
  { id: "n5-062", level: "N5", kanji: "来る", kana: "くる", meaning: "오다", pos: "동사",
    example_ja: "友達がうちに来ます。", example_reading: "ともだちがうちにきます。", example_ko: "친구가 집에 옵니다." },
  { id: "n5-063", level: "N5", kanji: "帰る", kana: "かえる", meaning: "돌아가다, 돌아오다", pos: "동사",
    example_ja: "もう家に帰ります。", example_reading: "もういえにかえります。", example_ko: "이제 집에 갑니다." },
  { id: "n5-064", level: "N5", kanji: "見る", kana: "みる", meaning: "보다", pos: "동사",
    example_ja: "テレビを見ます。", example_reading: "テレビをみます。", example_ko: "TV를 봅니다." },
  { id: "n5-065", level: "N5", kanji: "聞く", kana: "きく", meaning: "듣다, 묻다", pos: "동사",
    example_ja: "音楽を聞きます。", example_reading: "おんがくをききます。", example_ko: "음악을 듣습니다." },
  { id: "n5-066", level: "N5", kanji: "話す", kana: "はなす", meaning: "이야기하다", pos: "동사",
    example_ja: "日本語で話しましょう。", example_reading: "にほんごではなしましょう。", example_ko: "일본어로 이야기합시다." },
  { id: "n5-067", level: "N5", kanji: "読む", kana: "よむ", meaning: "읽다", pos: "동사",
    example_ja: "毎日本を読みます。", example_reading: "まいにちほんをよみます。", example_ko: "매일 책을 읽습니다." },
  { id: "n5-068", level: "N5", kanji: "書く", kana: "かく", meaning: "쓰다", pos: "동사",
    example_ja: "手紙を書きます。", example_reading: "てがみをかきます。", example_ko: "편지를 씁니다." },
  { id: "n5-069", level: "N5", kanji: "食べる", kana: "たべる", meaning: "먹다", pos: "동사",
    example_ja: "朝ごはんにパンを食べる。", example_reading: "あさごはんにパンをたべる。", example_ko: "아침밥으로 빵을 먹는다." },
  { id: "n5-070", level: "N5", kanji: "飲む", kana: "のむ", meaning: "마시다", pos: "동사",
    example_ja: "コーヒーを飲みます。", example_reading: "コーヒーをのみます。", example_ko: "커피를 마십니다." },
  { id: "n5-071", level: "N5", kanji: "買う", kana: "かう", meaning: "사다", pos: "동사",
    example_ja: "コンビニでパンを買いました。", example_reading: "コンビニでパンをかいました。", example_ko: "편의점에서 빵을 샀습니다." },
  { id: "n5-072", level: "N5", kanji: "売る", kana: "うる", meaning: "팔다", pos: "동사",
    example_ja: "この店は花を売っています。", example_reading: "このみせははなをうっています。", example_ko: "이 가게는 꽃을 팔고 있습니다." },
  { id: "n5-073", level: "N5", kanji: "作る", kana: "つくる", meaning: "만들다", pos: "동사",
    example_ja: "母がケーキを作りました。", example_reading: "ははがケーキをつくりました。", example_ko: "어머니가 케이크를 만들었습니다." },
  { id: "n5-074", level: "N5", kanji: "使う", kana: "つかう", meaning: "사용하다", pos: "동사",
    example_ja: "このペンを使ってください。", example_reading: "このペンをつかってください。", example_ko: "이 펜을 사용해 주세요." },
  { id: "n5-075", level: "N5", kanji: "立つ", kana: "たつ", meaning: "서다", pos: "동사",
    example_ja: "前に立ってください。", example_reading: "まえにたってください。", example_ko: "앞에 서 주세요." },
  { id: "n5-076", level: "N5", kanji: "座る", kana: "すわる", meaning: "앉다", pos: "동사",
    pitch_pattern: [0, 1, 1],
    example_ja: "椅子に座ります。", example_reading: "いすにすわります。", example_ko: "의자에 앉습니다.",
    roleplay_context: {
      situation: "신주쿠 이자카야에서 점원에게 자리 안내를 받는 상황",
      ai_role: "활기찬 이자카야 점원",
      initial_msg: "いらっしゃいませ！何名様ですか？お席にご案内します。",
      mission_keywords: ["座る", "二人", "ビール"],
    } },
  { id: "n5-077", level: "N5", kanji: "起きる", kana: "おきる", meaning: "일어나다", pos: "동사",
    example_ja: "毎朝六時に起きます。", example_reading: "まいあさろくじにおきます。", example_ko: "매일 아침 6시에 일어납니다." },
  { id: "n5-078", level: "N5", kanji: "寝る", kana: "ねる", meaning: "자다", pos: "동사",
    example_ja: "夜十一時に寝ます。", example_reading: "よるじゅういちじにねます。", example_ko: "밤 11시에 잡니다." },
  { id: "n5-079", level: "N5", kanji: "歩く", kana: "あるく", meaning: "걷다", pos: "동사",
    example_ja: "駅まで歩きます。", example_reading: "えきまであるきます。", example_ko: "역까지 걷습니다." },
  { id: "n5-080", level: "N5", kanji: "走る", kana: "はしる", meaning: "달리다", pos: "동사",
    example_ja: "公園で走ります。", example_reading: "こうえんではしります。", example_ko: "공원에서 달립니다." },
  { id: "n5-081", level: "N5", kanji: "大きい", kana: "おおきい", meaning: "크다", pos: "い형용사",
    example_ja: "この犬は大きいです。", example_reading: "このいぬはおおきいです。", example_ko: "이 개는 큽니다." },
  { id: "n5-082", level: "N5", kanji: "小さい", kana: "ちいさい", meaning: "작다", pos: "い형용사",
    example_ja: "小さい鞄が欲しいです。", example_reading: "ちいさいかばんがほしいです。", example_ko: "작은 가방을 갖고 싶습니다." },
  { id: "n5-083", level: "N5", kanji: "新しい", kana: "あたらしい", meaning: "새롭다", pos: "い형용사",
    example_ja: "新しいスマホを買いました。", example_reading: "あたらしいスマホをかいました。", example_ko: "새 스마트폰을 샀습니다." },
  { id: "n5-084", level: "N5", kanji: "古い", kana: "ふるい", meaning: "오래되다", pos: "い형용사",
    example_ja: "この建物は古いです。", example_reading: "このたてものはふるいです。", example_ko: "이 건물은 오래되었습니다." },
  { id: "n5-085", level: "N5", kanji: "良い", kana: "いい", meaning: "좋다", pos: "い형용사",
    example_ja: "今日はいい天気ですね。", example_reading: "きょうはいいてんきですね。", example_ko: "오늘은 좋은 날씨네요." },
  { id: "n5-086", level: "N5", kanji: "悪い", kana: "わるい", meaning: "나쁘다", pos: "い형용사",
    example_ja: "天気が悪いです。", example_reading: "てんきがわるいです。", example_ko: "날씨가 나쁩니다." },
  { id: "n5-087", level: "N5", kanji: "暑い", kana: "あつい", meaning: "덥다", pos: "い형용사",
    example_ja: "今日はとても暑いです。", example_reading: "きょうはとてもあついです。", example_ko: "오늘은 매우 덥습니다." },
  { id: "n5-088", level: "N5", kanji: "寒い", kana: "さむい", meaning: "춥다", pos: "い형용사",
    example_ja: "冬は寒いです。", example_reading: "ふゆはさむいです。", example_ko: "겨울은 춥습니다." },
  { id: "n5-089", level: "N5", kanji: "熱い", kana: "あつい", meaning: "뜨겁다", pos: "い형용사",
    example_ja: "熱いお茶を飲みます。", example_reading: "あついおちゃをのみます。", example_ko: "뜨거운 차를 마십니다." },
  { id: "n5-090", level: "N5", kanji: "冷たい", kana: "つめたい", meaning: "차갑다", pos: "い형용사",
    example_ja: "冷たい水をください。", example_reading: "つめたいみずをください。", example_ko: "차가운 물을 주세요." },
  { id: "n5-091", level: "N5", kanji: "高い", kana: "たかい", meaning: "높다, 비싸다", pos: "い형용사",
    pitch_pattern: [0, 1, 1],
    example_ja: "この鞄は高いです。", example_reading: "このかばんはたかいです。", example_ko: "이 가방은 비쌉니다.",
    roleplay_context: {
      situation: "오사카 신사이바시 옷가게에서 점원과 흥정하는 상황",
      ai_role: "재치 있는 옷가게 점원",
      initial_msg: "そのシャツ、似合いますね！どうですか？",
      mission_keywords: ["高い", "安い", "買う"],
    } },
  { id: "n5-092", level: "N5", kanji: "安い", kana: "やすい", meaning: "싸다", pos: "い형용사",
    example_ja: "ここは安くておいしいです。", example_reading: "ここはやすくておいしいです。", example_ko: "여기는 싸고 맛있습니다." },
  { id: "n5-093", level: "N5", kanji: "面白い", kana: "おもしろい", meaning: "재미있다", pos: "い형용사",
    example_ja: "この本はとても面白いです。", example_reading: "このほんはとてもおもしろいです。", example_ko: "이 책은 매우 재미있습니다." },
  { id: "n5-094", level: "N5", kanji: "楽しい", kana: "たのしい", meaning: "즐겁다", pos: "い형용사",
    example_ja: "旅行はとても楽しかったです。", example_reading: "りょこうはとてもたのしかったです。", example_ko: "여행은 매우 즐거웠습니다." },
  { id: "n5-095", level: "N5", kanji: "難しい", kana: "むずかしい", meaning: "어렵다", pos: "い형용사",
    example_ja: "日本語は難しいですか。", example_reading: "にほんごはむずかしいですか。", example_ko: "일본어는 어렵습니까?" },
  { id: "n5-096", level: "N5", kanji: "易しい", kana: "やさしい", meaning: "쉽다, 다정하다", pos: "い형용사",
    example_ja: "このテストは易しいです。", example_reading: "このテストはやさしいです。", example_ko: "이 시험은 쉽습니다." },
  { id: "n5-097", level: "N5", kanji: "綺麗", kana: "きれい", meaning: "예쁘다, 깨끗하다", pos: "な형용사",
    example_ja: "部屋がきれいですね。", example_reading: "へやがきれいですね。", example_ko: "방이 깨끗하네요." },
  { id: "n5-098", level: "N5", kanji: "元気", kana: "げんき", meaning: "건강함, 활기참", pos: "な형용사",
    example_ja: "お元気ですか。", example_reading: "おげんきですか。", example_ko: "잘 지내세요?" },
  { id: "n5-099", level: "N5", kanji: "静か", kana: "しずか", meaning: "조용함", pos: "な형용사",
    example_ja: "図書館は静かです。", example_reading: "としょかんはしずかです。", example_ko: "도서관은 조용합니다." },
  { id: "n5-100", level: "N5", kanji: "好き", kana: "すき", meaning: "좋아함", pos: "な형용사",
    example_ja: "音楽が好きです。", example_reading: "おんがくがすきです。", example_ko: "음악을 좋아합니다." },
  { id: "n5-101", level: "N5", kanji: "嫌い", kana: "きらい", meaning: "싫어함", pos: "な형용사",
    example_ja: "虫が嫌いです。", example_reading: "むしがきらいです。", example_ko: "벌레를 싫어합니다." },
  { id: "n5-102", level: "N5", kanji: "有名", kana: "ゆうめい", meaning: "유명함", pos: "な형용사",
    example_ja: "この店は有名です。", example_reading: "このみせはゆうめいです。", example_ko: "이 가게는 유명합니다." },
  { id: "n5-103", level: "N5", kanji: "便利", kana: "べんり", meaning: "편리함", pos: "な형용사",
    example_ja: "スマホはとても便利です。", example_reading: "スマホはとてもべんりです。", example_ko: "스마트폰은 매우 편리합니다." },
  { id: "n5-104", level: "N5", kanji: "一", kana: "いち", meaning: "1, 하나", pos: "수사",
    example_ja: "一つください。", example_reading: "ひとつください。", example_ko: "하나 주세요." },
  { id: "n5-105", level: "N5", kanji: "二", kana: "に", meaning: "2, 둘", pos: "수사",
    example_ja: "二人で行きます。", example_reading: "ふたりでいきます。", example_ko: "둘이서 갑니다." },
  { id: "n5-106", level: "N5", kanji: "三", kana: "さん", meaning: "3, 셋", pos: "수사",
    pitch_pattern: [1, 0],
    example_ja: "三時に会いましょう。", example_reading: "さんじにあいましょう。", example_ko: "3시에 만납시다.",
    roleplay_context: {
      situation: "교토 료칸 예약 확인 전화를 받는 상황",
      ai_role: "공손한 료칸 여주인",
      initial_msg: "もしもし、ご予約の件でお電話しました。何名様で何泊のご予定ですか？",
      mission_keywords: ["三", "二", "予約"],
    } },
  { id: "n5-107", level: "N5", kanji: "十", kana: "じゅう", meaning: "10, 열", pos: "수사",
    example_ja: "十分待ってください。", example_reading: "じゅっぷんまってください。", example_ko: "10분 기다려 주세요." },
  { id: "n5-108", level: "N5", kanji: "百", kana: "ひゃく", meaning: "100, 백", pos: "수사",
    example_ja: "百円ショップで買いました。", example_reading: "ひゃくえんショップでかいました。", example_ko: "100엔샵에서 샀습니다." },
  { id: "n5-109", level: "N5", kanji: "千", kana: "せん", meaning: "1,000, 천", pos: "수사",
    example_ja: "千円札を出します。", example_reading: "せんえんさつをだします。", example_ko: "천 엔짜리를 냅니다." },
  { id: "n5-110", level: "N5", kanji: "万", kana: "まん", meaning: "10,000, 만", pos: "수사",
    example_ja: "一万円を払いました。", example_reading: "いちまんえんをはらいました。", example_ko: "1만 엔을 냈습니다." },
];

export function getWordsByLevel(level: JlptLevel): Word[] {
  if (level === "N5") return N5_WORDS;
  return [];
}

export function getStageCount(level: JlptLevel): number {
  const words = getWordsByLevel(level);
  return Math.ceil(words.length / STAGE_SIZE);
}

export function getStageWords(level: JlptLevel, day: number): Word[] {
  const words = getWordsByLevel(level);
  const start = (day - 1) * STAGE_SIZE;
  return words.slice(start, start + STAGE_SIZE);
}

export const LEVEL_META: Record<JlptLevel, { ready: boolean; total: number; desc: string }> = {
  N5: { ready: true, total: N5_WORDS.length, desc: "처음 시작해요" },
  N4: { ready: false, total: 0, desc: "기초는 떼었어요" },
  N3: { ready: false, total: 0, desc: "일상회화 도전" },
  N2: { ready: false, total: 0, desc: "중상급 어휘" },
  N1: { ready: false, total: 0, desc: "최고 레벨" },
};
